#!/bin/bash
set -x

function wait () {
echo Sleeping for $1 seconds ...
sleep $1
}

function ismounted () {
MNTPT=${1}
mount | grep " $MNTPT "
RET=$?
if [ "$RET" = "0" ]
then
	true
else
	false
fi
}

function retry() {
CMD=$1
MAXRETRY=$2
MSG=$3
COUNT=1

while [ $COUNT -lt $MAXRETRY ]
do
	echo "$MSG [try $COUNT]"
	$CMD
	if [[ $? = 0 ]]
	then
		SUCCESS=true
		break
	fi
	COUNT=$(($COUNT+1))
	sleep 1
done

if [ $SUCCESS = true ]
then
	echo "$MSG succesfull [ $COUNT tries]"
else
	echo "$MSG failed"
fi 
}

function umountretry() {
MNTPT=${1}

if ( ismounted $MNTPT )
then
	retry "umount $MNTPT" 10 "Umounting $MNTPT"
else
	echo "$MNTPT not mounted"
fi
}


cd /
echo Starting post backup job
umountretry /mnt/backup/boot 10

set -x
for VOLUME in home root
do
	
	LVSRC=$VOLUME
	SNAPNAME="${LVSRC}sn"
	ORIMNT=$(mount | grep "/dev/mapper/junovg0-${VOLUME} " | cut -f 3 --delimiter=' ')
	ORIMNT=${ORIMNT%/}
	ORIMNT=${ORIMNT#/}
	MNTPT=/mnt/backup/${ORIMNT}
	MNTPT=${MNTPT%/}
	cd /
	echo Umounting $MNTPT
	umountretry $MNTPT 10
	echo Removing $SNAPNAME
	lvremove -f /dev/mapper/junovg0-$SNAPNAME || \
	lvremove -f /dev/mapper/junovg0-$SNAPNAME
done

if [ "$1" != "nosuspend" ]
then
	echo /home/diesis/local/bin/sospendi
fi

